### ISSUE TITLE
Upgrade camel.version to 3.14.1 (was 3.10.0)

### ISSUE THREAD

**Issue by ceefour** [camunda-community-hub/camunda-bpm-camel#63]

**Comment by berndruecker** [comment]
Hey @ceefour - thanks for raising this issue. Is there any work required to make it work with Camel 3.10.0 or couldn't you simply use it with that version?

**Comment by ceefour** [comment]
I have tried simply overriding the camel versions with 3.10.0, and works well.

So in this case, I'm requesting that the camunda-bpm-camel upgrades to 3.10.0 as upstream.

**Comment by berndruecker** [comment]
Playing devils advocate try to understand the advantage of upgrading the version if we don't need to, many projects can be used in conjunction with newer releases of the libraries they are built against - no?

**Comment by ceefour** [comment]
My argument would be that it's a "saner" default, especially that the 3.2.0 version is old enough, not just few minor versions behind.

A project that wants an older version can still do so, but I'd say that's a less likely scenario.

Normally a project wants to use current Camel version.

**Comment by berndruecker** [comment]
I did a quick stab, but the project does not compile with 3.10.0:

```
ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project camunda-bpm-camel-common: Compilation failure: Compilation failure:
[ERROR] /C:/DEV/Camunda/camunda-bpm-camel/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/component/CamundaBpmPollExternalTasksEndpointImpl.java:[27,37] package org.apache.camel.catalog.impl does not exist
[ERROR] /C:/DEV/Camunda/camunda-bpm-camel/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/component/CamundaBpmProcessExternalTaskEndpointImpl.java:[15,37] package org.apache.camel.catalog.impl does not exist
[ERROR] /C:/DEV/Camunda/camunda-bpm-camel/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/component/CamundaBpmPollExternalTasksEndpointImpl.java:[75,33] cannot find symbol
[ERROR]   symbol:   variable TimePatternConverter
[ERROR]   location: class org.camunda.bpm.camel.component.CamundaBpmPollExternalTasksEndpointImpl
[ERROR] /C:/DEV/Camunda/camunda-bpm-camel/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/component/CamundaBpmPollExternalTasksEndpointImpl.java:[85,36] cannot find symbol
[ERROR]   symbol:   variable TimePatternConverter
[ERROR]   location: class org.camunda.bpm.camel.component.CamundaBpmPollExternalTasksEndpointImpl
[ERROR] /C:/DEV/Camunda/camunda-bpm-camel/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/component/CamundaBpmPollExternalTasksEndpointImpl.java:[104,33] cannot find symbol
[ERROR]   symbol:   variable TimePatternConverter
[ERROR]   location: class org.camunda.bpm.camel.component.CamundaBpmPollExternalTasksEndpointImpl
[ERROR] /C:/DEV/Camunda/camunda-bpm-camel/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/component/CamundaBpmProcessExternalTaskEndpointImpl.java:[55,33] cannot find symbol
[ERROR]   symbol:   variable TimePatternConverter
[ERROR]   location: class org.camunda.bpm.camel.component.CamundaBpmProcessExternalTaskEndpointImpl
[ERROR] /C:/DEV/Camunda/camunda-bpm-camel/camunda-bpm-camel-common/src/main/java/org/camunda/bpm/camel/component/CamundaBpmProcessExternalTaskEndpointImpl.java:[65,36] cannot find symbol
[ERROR]   symbol:   variable TimePatternConverter
[ERROR]   location: class org.camunda.bpm.camel.component.CamundaBpmProcessExternalTaskEndpointImpl
[ERROR] -> [Help 1]
```

Are you willing to provide a PR looking into this?

**Comment by jangalinski** [comment]
fixed with #96
